name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src  # Path to the folder you want to publish
          publish_branch: gh-pages  # Branch to deploy to
          force_orphan: true  # Create an orphan branch if gh-pages doesn't exist
